F9Aup
Seagate/cortx-test pull request #1377
Opened 2022-03-21 10:01 UTC by Kulkarni-Kaustubh

Signed-off-by: Kaustubh Kulkarni <kaustubh.j.kulkarni@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide
[collections_log.txt](https://github.com/Seagate/cortx-test/files/8314530/collections_log.txt)
[Log file.txt](https://github.com/Seagate/cortx-test/files/8314531/Log.file.txt)

2022-03-21 10:06 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +    @pytest.mark.comp_prov
Please dont use comp_prov markers for cft tests

2022-03-21 10:10 UTC, priyankaborawake commented on libs/prov/prov_k8s_cortx_deploy.py
> +        cmd = "cd {}; {}".format(PROV_CFG['k8s_cortx_deploy']["git_remote_path"], upgrade_cmd)
Please add this in try except block and return false if failure in upgrade command

2022-03-21 10:12 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +    def perform_upgrade(self, upgrade_image_version: str, exc: bool = True):
This method is not required, service_upgrade_software can be used directly in test.

2022-03-21 10:14 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +"""Provisioner Component level test cases for K8s CORTX Software Upgrade."""
Please update the correct description

2022-03-21 10:17 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +            assert_utils.assert_true(resp[0],"Installed version is same or higher than installing version." )
Add False instead of resp[0]

2022-03-21 10:18 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +        # TODO : Use data-pod when cortx services framework is done.
Remove TODO as its already done.

2022-03-21 10:20 UTC, priyankaborawake commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +        LOGGER.info("New CORTX image version: %s", new_installed_version)
Please compare if  new_installed_version and upgrade_image_version  are equal.

2022-03-21 10:30 UTC, priyankaborawake requested changes
@Kulkarni-Kaustubh  added few comments, please check

2022-03-21 13:03 UTC, pragamj commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +    @classmethod
why classmethod

2022-03-21 13:54 UTC, pragamj commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +        cls.que = queue.queue()
is this used ?

2022-03-21 14:10 UTC, pragamj approved these changes

2022-03-22 06:15 UTC, priyankaborawake approved these changes

2022-03-22 06:35 UTC, swapnil-khandare commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +    @pytest.mark.tags("TEST-33660")
you may need to add marker for test

2022-03-22 06:35 UTC, swapnil-khandare commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +    @pytest.mark.tags("TEST-33669")
you may need to add marker for test

2022-03-22 07:20 UTC, swapnil-khandare approved these changes

2022-03-22 07:57 UTC, seagate-sarang-sawant approved these changes

2022-03-31 12:30 UTC, pragamj commented on config/prov/prov_test.yaml
> -  k8s_dir: "/root/deploy-scripts/k8_cortx_cloud/"
keep deploy-scripts

2022-03-31 12:30 UTC, pragamj commented on tests/prov/test_prov_k8s_cortx_upgrade.py
> +=======
remove these <<<<<

2022-04-01 08:29 UTC, merged