Test to automate create-list-delete 1000 buckets and also list bucket operation for bucket names within range 3-63 chars long
Seagate/cortx-test pull request #1429
Opened 2022-04-11 10:31 UTC by kapiljinna

Test to automate create-list-delete 1000 buckets and also list bucket operation for bucket names within range 3-63 chars long using the default user credentials .

Signed-off-by: Kapil Jinna <kapil.jinna@seagate.com>

# Problem Statement
Automate below tests using default user credentials:
- For creating-listing-deleting 1000 buckets .
- Verify list bucket operation for bucket names within range 3-63 chars long .

# Design
TEST JIRA ids to be automated :
-https://jts.seagate.com/browse/TEST-36100
-https://jts.seagate.com/browse/TEST-36157

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-05-26 16:57 UTC, seagate-sarang-sawant approved these changes

2022-06-15 07:35 UTC, DhobaleVishal requested changes
@kapiljinna Added inline comments. Please fix codacy issues.

2022-06-15 07:35 UTC, DhobaleVishal commented on comptests/s3/test_bkt_crud_operations_rgw.py
> +            assert resp[0], resp[1]
Use assert_utils for any type of assert.

2022-06-15 07:35 UTC, DhobaleVishal commented on comptests/s3/test_bkt_crud_operations_rgw.py
> +        self.log.info(resp)
Avoid repeated logging as same was done in s3 libs.

2022-06-15 07:35 UTC, DhobaleVishal commented on comptests/s3/test_bkt_crud_operations_rgw.py
> +    @pytest.mark.lc
I think this label no more required. Please remove it.

2024-02-08 16:47 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:47 UTC, closed without merging