Cortx 30580
Seagate/cortx-test pull request #1524
Opened 2022-05-11 06:29 UTC by archanabpatil

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-05-11 09:13 UTC, apoorva-rao requested changes
@archanabpatil one minor comment added inline

2022-05-11 09:13 UTC, apoorva-rao commented on tests/s3/multipart_upload/test_multipart_getput.py
> +                                args=(self.bucket_name, self.object_name),
Indentation needs to be tweaked for lines 816 and 817

2022-05-11 09:28 UTC, apoorva-rao approved these changes

2022-05-13 07:39 UTC, seagate-sarang-sawant approved these changes

2022-05-16 12:59 UTC, merged