codacy fix for iam_core_lib
Seagate/cortx-test pull request #1565
Opened 2022-05-19 05:01 UTC by archanabpatil

Signed-off-by: archanabpatil <66412855+archanabpatil@users.noreply.github.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-05-19 05:34 UTC, apoorva-rao requested changes
@archanabpatil please see the inline comment

2022-05-19 05:34 UTC, apoorva-rao commented on libs/s3/iam_core_lib.py
> +        # pylint: disable=broad-except
Rather than disabling the Codacy warning let's narrow down scope of the except block by specifying the botocore.exceptions.ClientError exception.

2022-05-20 04:32 UTC, apoorva-rao approved these changes

2022-05-20 04:33 UTC, sonalk0209 approved these changes

2022-05-20 04:51 UTC, merged