Codacy fix part 2
Seagate/cortx-test pull request #1615
Opened 2022-05-31 10:35 UTC by pragamj

# Problem Statement
- Codacy_fix_phase2

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)
[collections_log.txt](https://github.com/Seagate/cortx-test/files/8804337/collections_log.txt)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-06-01 06:27 UTC, ketanarlulkar commented on tests/prov/test_prov_single_node.py
>      @pytest.mark.tags("TEST-19439")
`teardown_method` could be function. Remove if nothing to teardown.

2022-06-01 06:29 UTC, ketanarlulkar commented on tests/prov/test_post_deploy_validation.py
>          set_timesrv_ip = (random.choice(
use of Standard pseudo-random generators on line 197 and 199 (random)

2022-06-01 06:31 UTC, ketanarlulkar commented on tests/prov/test_post_deploy_validation.py
>                  exp_t_srv=self.ntp_data["srvnode-1"][self.ntp_keys[0]],
Line 407 CSM_USER prefer snake_case

2022-06-01 06:34 UTC, ketanarlulkar requested changes
Check comments

2022-06-01 13:31 UTC, sonalk0209 approved these changes

2022-06-02 03:31 UTC, ketanarlulkar approved these changes

2022-06-02 03:37 UTC, merged