two more test cases : TEST-40431, 40432
Seagate/cortx-test pull request #1650
Opened 2022-06-09 18:31 UTC by rahul-hatwar

Signed-off-by: RAHUL HATWAR <rahulchandrakant.hatwar@seagate.com>

# Problem Statement
TWO more test cases : TEST-40431 and TEST-40432

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-06-10 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_get_put_object_tagging.py
> +        resp = self.s3_test_obj.put_object(bucket_name=self.bucket_name,
You would need to call upload_version with chk_null_version=True here, since bucket is Suspended

2022-06-10 09:24 UTC, apoorva-rao requested changes
@rahul-hatwar added some minor comments inline, please check them

2022-06-10 09:24 UTC, apoorva-rao commented on tests/s3/versioning/test_get_put_object_tagging.py
> +    def test_get_put_obj_tags_bkt_40431(self):
Test method name can be tweaked to indicate it is on a versioned bucket

2022-06-10 09:24 UTC, apoorva-rao commented on tests/s3/versioning/test_get_put_object_tagging.py
> +        resp = self.s3_test_obj.put_object(bucket_name=self.bucket_name,
You would need to call upload_version with chk_null_version=True here, since bucket is Suspended

2022-06-10 10:36 UTC, apoorva-rao approved these changes

2022-06-10 12:06 UTC, VikasKumarC approved these changes

2022-06-13 02:21 UTC, ankita-93 approved these changes

2022-06-13 05:07 UTC, sonalk0209 approved these changes
Approve to merge!!!

2022-06-13 05:07 UTC, merged