TA for DeleteObjectTagging & Get object tags count using get-object
Seagate/cortx-test pull request #1654
Opened 2022-06-10 09:33 UTC by akshaym99

Signed-off-by: akshaym99 <akshay.s.mankar@seagate.com>

# Problem Statement
- Test Automation for F-28B: DeleteObjectTagging & Get object tags count using get-object
-  TEST-42780, TEST-42781, TEST-42782

# Design
-  TD doc: https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/983465985/F-28B+S3+Object+Tagging+API 

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-06-10 09:34 UTC, akshaym99 commented
@apoorva-rao , @DhobaleVishal, @VikasKumarC Please review

2022-06-10 10:33 UTC, DhobaleVishal requested changes

2022-06-10 11:34 UTC, akshaym99 commented
Pytest collection is green:
sts/security/test_cortx_port_scanner_netstat.py::test_cortx_port_scanner_netstat', 'test_id': 'TEST-34218', 'marks': ['security', 'skip']}] created at /root/akshay/cortx-test-1/log/te_meta.json
Successfully unmounted directory

===================================================================== 2269 tests collected in 8.34s ======================================================================
(virenv) [root@ssc-vm-g4-rhev4-0125 cortx-test-1]#

2022-06-10 11:37 UTC, akshaym99 commented on tests/s3/test_object_tagging.py
> +    @CTFailOn(error_handler)
Removed particular decorator.

2022-06-10 12:20 UTC, apoorva-rao requested changes
@akshaym99 one minor comment added inline

2022-06-13 08:38 UTC, akshaym99 commented on tests/s3/test_object_tagging.py
> +        self.log.info("Verify already deleted tag using DELETE object tagging")
Step is added.

2022-06-13 10:31 UTC, apoorva-rao approved these changes

2022-06-14 04:09 UTC, DhobaleVishal requested changes

2022-06-14 04:09 UTC, DhobaleVishal commented on tests/s3/test_object_tagging.py
> +                error.message), error.message
```suggestion
            assert_utils.assert_in(S3_OBJ_TST["s3_object"]["key_err"], str(error.message), error.message)
```

2022-06-14 04:12 UTC, akshaym99 commented on tests/s3/test_object_tagging.py
> +                error.message), error.message
Done.

2022-06-14 04:13 UTC, DhobaleVishal approved these changes
LGTM

2022-06-14 04:29 UTC, VikasKumarC approved these changes

2022-06-14 05:24 UTC, sonalk0209 approved these changes
Approving for merge!!!

2022-06-14 05:24 UTC, merged