Policy operations are moved to test_user_policy_crud.py
Seagate/cortx-test pull request #1685
Opened 2022-06-17 09:37 UTC by Naveen-Kumar-seagate

Signed-off-by: Naveen-Kumar-seagate <siriga.naveenkumargowd@seagate.com>

# Problem Statement
- Policy operations are moved to test_user_policy_crud.py

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-06-20 06:36 UTC, ravindrachoudhari approved these changes

2022-06-23 05:02 UTC, seagate-sarang-sawant requested changes

2022-06-23 05:02 UTC, seagate-sarang-sawant commented on comptests/s3/test_user_policy_crud.py
> +        loop = asyncio.get_event_loop()
Extract out the commonly used functions like create user and create policy into generic functions and  push it down to test lib layer.

2022-06-27 11:51 UTC, seagate-sarang-sawant approved these changes

2022-06-27 11:51 UTC, seagate-sarang-sawant commented on comptests/s3/test_user_policy_crud.py
> +        status = loop.run_until_complete(self.obj.put_user_policy(user_params))
You could have removed asyncio event loop.  run_until_complete is not going to retry in case of failure or socked exception.

2022-06-27 12:02 UTC, merged