Cortx-29601: RBF for Object tagging versioning
Seagate/cortx-test pull request #1701
Opened 2022-06-24 07:11 UTC by AshwiniS-Borse

# Problem Statement
- RBF for object tagging versioning test cases.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [x] Attach test execution logs
-  [x] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-06-27 06:47 UTC, AshwiniS-Borse commented
pytest collection is green.

Execution logs are present in below TE:
https://jts.seagate.com/browse/TEST-43767.
Below 2 tests are failed because of existing sev-3 defects
[TEST-40438](https://jts.seagate.com/browse/TEST-40438)
[TEST-40439](https://jts.seagate.com/browse/TEST-40439)

2022-06-27 06:47 UTC, AshwiniS-Borse commented
@apoorva-rao @VikasKumarC @DhobaleVishal @archanabpatil Please review PR

2022-06-27 09:20 UTC, apoorva-rao requested changes
@AshwiniS-Borse changes look good, added minor comments inline for indentation

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                s3_ver_test_obj=self.s3_ver_obj,
Let's correct the indentation for 487 - 493

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                s3_ver_test_obj=self.s3_ver_obj,
Let's correct the indentation here

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                    f"Expected: {put_tag} \n Actual: {get_tag}")
Let's correct indentation here

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                    {"Key": "tag,key", "Value": "tag1value"}]
indentation correction needed

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                s3_ver_test_obj=self.s3_ver_obj,
indentation correction needed

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                s3_ver_test_obj=self.s3_ver_obj,
Let's correct indentation

2022-06-27 09:20 UTC, apoorva-rao commented on tests/s3/versioning/test_limits_tagging_versioning.py
> +                                                    f"Expected: {put_tag} \n Actual: {get_tag1}")
Let's correct the indentation here

2022-06-28 06:53 UTC, apoorva-rao approved these changes

2022-06-28 06:59 UTC, archanabpatil reviewed
pls fix codacy

2022-06-28 06:59 UTC, archanabpatil commented on config/s3/s3_config.yaml
> +object_tagging_special_char_rgw: ["~", "`", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "+", "=", ";", ":", "|", "\\", ":", ";", "\"", "'", "<", ",", ">", ".", "?", "/"]
is this mentioned somewhere?

2022-06-28 07:30 UTC, DhobaleVishal approved these changes
@AshwiniS-Borse Make sure changes verified by executing on latest cortx-rgw build..

2022-06-28 10:23 UTC, VikasKumarC approved these changes

2022-06-28 12:11 UTC, ravindrachoudhari approved these changes

2022-06-28 12:11 UTC, merged