TEST-41747 - Motr DI
Seagate/cortx-test pull request #1763
Opened 2022-07-19 03:46 UTC by pranav-sahasrabudhe

# Problem Statement
- TEST-41747 Parity corruption and detection with M0cp and M0cat and Error_Detection.py script 

# Design
-  Parity corruption and detection with M0cp and M0cat and Error_Detection.py script 

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-08-10 09:06 UTC, pragamj commented on comptests/motr/test_motr_di.py
> +        return True  # Todo: return status to be worked as per responses
We won't require return statement as in the individual function of m0cp/m0cat/md5sum,unlink have assert.

2022-08-10 09:07 UTC, pragamj commented on comptests/motr/test_motr_di.py
> +                    b_size, cnt_c, object_id, layout, infile, node_pod, 0
client count is set to 0 ?

2022-08-10 09:09 UTC, pragamj commented on comptests/motr/test_motr_di.py
> +                bsize_list, count_list, layout_ids, offsets
we can remove offsets , if its not used

2022-08-10 09:10 UTC, pragamj requested changes
Added few review comments.

2024-02-08 16:45 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:45 UTC, closed without merging