Automated TEST-19842
Seagate/cortx-test pull request #1773
Opened 2022-07-26 09:11 UTC by ketanarlulkar

# Problem Statement
- Automated test defined at _Table2 : Parallel Copy Operation of same source and destination_ in [TDS: F-20A: S3 Copy Object API](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1079640340/TDS+F-20A+S3+Copy+Object+API)

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-07-29 12:40 UTC, archanabpatil requested changes

2022-07-29 12:40 UTC, archanabpatil commented on tests/s3/copy_object/test_parallel_copy_object.py
> +        self.create_put_object("src-bucket", "obj1", 100)
make this 5gb object for variation

2022-07-29 12:40 UTC, archanabpatil commented on tests/s3/copy_object/test_parallel_copy_object.py
> +        self.s3mp_obj.simple_multipart_upload("src-bucket", "obj3", 1024, self.file_path, 4)
lets make it 3 gb object and rename it to mp-obj1 like above tests. I will modify name in tds and test

2022-07-29 12:41 UTC, archanabpatil commented
I have updated the object names wherever I had asked in this PR to tds and in tests

2022-08-01 11:49 UTC, archanabpatil commented on tests/s3/copy_object/test_parallel_copy_object.py
> +
blank line

2022-08-01 12:22 UTC, archanabpatil approved these changes

2022-08-02 05:24 UTC, AshwiniS-Borse commented on libs/s3/s3_multipart_test_lib.py
> +        by dividing it into given number of parts.
Need to add return param as well.

2022-08-02 05:42 UTC, AshwiniS-Borse approved these changes

2022-08-02 06:05 UTC, ravindrachoudhari commented on tests/s3/copy_object/test_parallel_copy_object.py
> +    @pytest.mark.tags("TEST-44786")
no other marker required?

2022-08-02 06:15 UTC, ketanarlulkar commented on tests/s3/copy_object/test_parallel_copy_object.py
> +    @pytest.mark.tags("TEST-44786")
Added markers

2022-08-02 06:19 UTC, ravindrachoudhari approved these changes

2022-08-02 06:19 UTC, merged