Added test TEST-45716
Seagate/cortx-test pull request #1804
Opened 2022-08-09 04:49 UTC by pragamj

Signed-off-by: pragam <pragam.jain@seagate.com>

# Problem Statement
- Added test TEST-45716 -Corrupt each data unit one by one and check Motr is able to detect read error for aligned data blocks

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)
[collections_log.txt](https://github.com/Seagate/cortx-test/files/9286814/collections_log.txt)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-08-09 14:53 UTC, pranav-sahasrabudhe requested changes
Overall looks good. Few minor var names changes.

2022-08-09 14:53 UTC, pranav-sahasrabudhe commented on libs/motr/emap_fi_adapter.py
> +        d_fid = []
optionally we can rename this var name to be more elaborate like `data_fid` and `parity_fid`

2022-08-12 05:58 UTC, ravindrachoudhari commented on libs/motr/emap_fi_adapter.py
> +                if pod_name == "cortx-data-g0-0":
we should avoid hardcoding of pod name.

2022-08-16 04:46 UTC, ravindrachoudhari approved these changes

2022-08-16 05:16 UTC, pranav-sahasrabudhe approved these changes

2022-08-16 05:35 UTC, merged