quick_fix_for_type_1
Seagate/cortx-test pull request #1856
Opened 2022-09-06 14:48 UTC by kulrk

Signed-off-by: kulrk <rohan.1.kulkarni@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-09-08 05:51 UTC, priyankaborawake commented on libs/iostability/iostability_lib.py
> +    def get_s3bench_logfile_label_from_test_log_file(self, test_log_file):
Can this be moved to s3bench lib ?

2022-09-08 06:04 UTC, priyankaborawake commented on libs/iostability/iostability_lib.py
> +                                       duration=None,
Please add logging before start of each operation.

2022-09-08 06:05 UTC, priyankaborawake commented on libs/iostability/iostability_lib.py
> +                assert not s3bench.check_log_file_error(resp[1]), \
Please add which operation failed in assert statement

2022-09-08 06:12 UTC, priyankaborawake requested changes
@kulrk Added minor comments. 
Please check.

2024-02-08 16:45 UTC, shailesh-vaidya commented
Closing as an obsolete

2024-02-08 16:45 UTC, closed without merging