Cortx 33524 testcases
Seagate/cortx-test pull request #1863
Opened 2022-09-07 15:32 UTC by pragamj

# Problem Statement
- Added test 42911 42912

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
-  [ ] New/Affected tests are executed on Latest Build
-  [ ] Attach test execution logs
[TEST-42911_TestCorruptDataDetection_20220907064715.log](https://github.com/Seagate/cortx-test/files/9507580/TEST-42911_TestCorruptDataDetection_20220907064715.log)
[TEST-42912_TestCorruptDataDetection_20220907072724.log](https://github.com/Seagate/cortx-test/files/9507581/TEST-42912_TestCorruptDataDetection_20220907072724.log)

-  [ ] Collection tested and no collection error introduced (`pytest --local True --collect-only`)
[collections_log.txt](https://github.com/Seagate/cortx-test/files/9507565/collections_log.txt)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
-  [ ] If change in any common function, make sure to update all calls and execute all affected tests.

# Documentation
  Checklist for Author
-  [ ] Changes done to ReadMe / WIKI / Confluence page / Quick Start Guide

2022-09-09 09:19 UTC, pranav-sahasrabudhe approved these changes
LGTM

2022-09-12 06:59 UTC, ketanarlulkar approved these changes

2022-09-12 07:01 UTC, priyankaborawake requested changes

2022-09-12 10:38 UTC, priyankaborawake requested changes
Please work on the codacy issues.

2022-09-12 11:38 UTC, pragamj commented
> Please work on the codacy issues.

Asked the gatekeepers to add those files in skip list

2022-09-12 11:47 UTC, priyankaborawake approved these changes

2022-09-13 02:35 UTC, ravindrachoudhari approved these changes

2022-09-13 05:14 UTC, merged